### ISSUE TITLE
Guppi Notes throws Win32Exception

### ISSUE THREAD

**Issue by rprouse** [rprouse/guppi#45]
It looks like the install location for VS Code changed with the latest release.

```
Unhandled exception: System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Guppi.Infrastructure.Services.Notes.NotesService.OpenNotes(Boolean nocreate, String filename) in /home/runner/work/guppi/guppi/Guppi.Infrastructure/Services/Notes/NotesService.cs:line 51
   at Guppi.Application.Commands.Notes.OpenNotesCommandHandler.Handle(OpenNotesCommand request, CancellationToken cancellationToken) in /home/runner/work/guppi/guppi/Guppi.Application/Commands/Notes/OpenNotesCommand.cs:line 21
```

New install location

```
"C:\Users\rob\AppData\Local\Programs\Microsoft VS Code\Code.exe"
```

**Comment by rprouse** [comment]
Invalid bug, I didn't realize I was running in a WSL terminal where I don't have code installed.
